import emailjs from"@emailjs/browser";emailjs.init("c0UqVFYtByUWzi-5c");let availability={Porto:{1:{daySlots:{2:[{start:"10:20",end:"13:20"},{start:"15:00",end:"19:00"}],5:[{start:"10:20",end:"13:20"},{start:"15:00",end:"19:00"}]}},2:{daySlots:{2:[{start:"15:00",end:"18:00"}]}}},"Santo Tirso":{1:{daySlots:{1:[{start:"15:00",end:"19:00"}],3:[{start:"09:00",end:"12:40"}]}}}},currentStep=0,currentLang=document.documentElement.lang||"pt-PT",steps=document.querySelectorAll(".form-step"),form=document.getElementById("appointmentForm"),weekLabel=document.getElementById("weekLabel"),calendarTable=document.getElementById("calendarTable"),selectedSlotInput=document.getElementById("selectedSlot"),specialty=form.elements.specialty,location=form.elements.location,currentYear=(new Date).getFullYear(),currentMonth=(new Date).getMonth(),currentMonday=getMonday(new Date(currentYear,currentMonth,1));function showStep(n){steps.forEach((e,t)=>e.classList.toggle("active",t===n))}function getMonday(e){var t=(e=new Date(e)).getDay(),t=e.getDate()-t+(0===t?-6:1);return new Date(e.setDate(t))}function timeToDate(e,t){var[t,n]=t.split(":").map(Number),e=new Date(e);return e.setHours(t,n,0,0),e}function generateTimeSlotsForDate(e,t,n,a){var r=[];let o=timeToDate(e,t);for(var l=timeToDate(e,n);o<=l;)r.push(new Date(o)),o=new Date(o.getTime()+6e4*a);return r}function renderCalendar(a){selectedSlotInput.value="";let r=availability[location.value]?.[specialty.selectedIndex];var e=document.querySelector(".calendar"),t=new Date(currentYear,currentMonth,1),t=t.toLocaleString(currentLang,{month:"long"})+" "+t.getFullYear();if(weekLabel.innerHTML=`
        <div class="calendar-header">
            <button onclick="changeMonth(-1)">&lt;</button>
            <strong>${t}</strong>
            <button onclick="changeMonth(1)">&gt;</button>
        </div>
    `,r&&r.daySlots){e.style.display="block";let n=[...Array(5)].map((e,t)=>{var n=new Date(a);return n.setDate(a.getDate()+t),n});var t=n.map(e=>`<th>${e.toLocaleDateString(currentLang,{weekday:"short",day:"numeric",month:"numeric"})}</th>`).join(""),o=generateTimeSlotsForDate(new Date,"09:00","19:00",20).map(e=>{let t=e.toTimeString().slice(0,5);return`<tr>${n.map(n=>{var e=n.getDay();let a=timeToDate(n,t);return`<td class="${(r.daySlots[e]||[]).some(e=>{var t=timeToDate(n,e.start),e=timeToDate(n,e.end);return a>=t&&a<=e})?"slot":"disabled-slot"}" data-slot="${n.toLocaleDateString()+" "+t}">${t}</td>`}).join("")}</tr>`});calendarTable.innerHTML=`
        <table>
            <thead><tr>${t}</tr></thead>
            <tbody>${o.join("")}</tbody>
        </table>
    `,document.querySelectorAll(".slot").forEach(e=>{e.addEventListener("click",()=>{document.querySelectorAll(".slot").forEach(e=>e.classList.remove("selected")),e.classList.add("selected"),selectedSlotInput.value=e.dataset.slot})})}else e.style.display="none",calendarTable.innerHTML=""}window.nextStep=function(){var e;for(e of steps[currentStep].querySelectorAll("input, select"))if(!e.checkValidity())return void e.reportValidity();showStep(++currentStep),renderCalendar(currentMonday)},window.prevStep=function(){showStep(--currentStep)},specialty.addEventListener("change",()=>renderCalendar(currentMonday)),location.addEventListener("change",()=>renderCalendar(currentMonday)),window.changeWeek=function(e){currentMonday.setDate(currentMonday.getDate()+7*e),currentYear=currentMonday.getFullYear(),currentMonth=currentMonday.getMonth(),renderCalendar(currentMonday)},window.changeMonth=function(e){var e=new Date(currentYear,currentMonth+e,1),t=e.getDay();6===t?e.setDate(e.getDate()+2):0===t&&e.setDate(e.getDate()+1),currentYear=e.getFullYear(),currentMonth=e.getMonth(),renderCalendar(currentMonday=getMonday(e))},form.addEventListener("submit",function(e){if(e.preventDefault(),!selectedSlotInput.value&&availability[form.elements.location.value]?.[form.elements.specialty.value])alert("Por favor selecione um horário.");else if(grecaptcha.getResponse()){let e={name:document.getElementById("name").value,email:document.getElementById("email").value,birthday:document.getElementById("birthday").value,contact:document.getElementById("contact").value,specialty:specialty.value,location:location.value,selectedSlot:selectedSlotInput.value||"Sem horário selecionado",notes:form.querySelector('[name="notes"]')?.value||""};emailjs.send("service_2mkemrj","template_yaezzgg",e).then(()=>{showStep(currentStep=0),emailjs.send("service_2mkemrj","template_ppny0sk",e).then(()=>{document.getElementById("statusMsg").textContent="Agendamento enviado com sucesso!",form.reset()}).catch(e=>{console.error("Erro no email do cliente:",e),document.getElementById("statusMsg").textContent="Erro ao enviar o e-mail de confirmação.",showStep(currentStep=0)})}).catch(e=>{console.error("Erro no email da clínica:",e),document.getElementById("statusMsg").textContent="Erro ao enviar. Tente novamente.",showStep(currentStep=0)})}else alert("Por favor confirma que não és um robô.")}),showStep(0);